### ISSUE TITLE
Move logos to SVG

### ISSUE THREAD

**Issue by Tom32i** [manala/website#3]
Move technos and corporate logos to SVG (rather than png) for better performances and rendering.

See: http://svgporn.com

**Comment by benji07** [comment]
http://svgporn.com/logos/ansible.svg
http://svgporn.com/logos/vagrant.svg
http://svgporn.com/logos/docker.svg

**Comment by Tom32i** [comment]
Improved integration: 

![capture d ecran 2016-06-22 a 14 25 34](https://cloud.githubusercontent.com/assets/1846873/16266489/71ea3c80-3885-11e6-9266-59054e0f5dba.png)
![capture d ecran 2016-06-22 a 14 25 41](https://cloud.githubusercontent.com/assets/1846873/16266488/71e9f176-3885-11e6-9e78-b9c3f0a1541c.png)
![capture d ecran 2016-06-22 a 14 25 53](https://cloud.githubusercontent.com/assets/1846873/16266487/71e75114-3885-11e6-8872-a54c742f95ad.png)
